delete from PizzaOrder_Pizzas;
delete from Pizza_Ingredients;
delete from Pizza;
delete from PizzaOrder;

delete from Ingredient;
insert into Ingredient (id, name, type) values ('SZYN', 'szynka', 'PROTEIN');
insert into Ingredient (id, name, type) values ('WOLO', 'wolowina', 'PROTEIN');
insert into Ingredient (id, name, type) values ('KURC', 'kurczak', 'PROTEIN');
insert into Ingredient (id, name, type) values ('GRKU', 'grillowany kurczak', 'PROTEIN');
insert into Ingredient (id, name, type) values ('PEPP', 'pepperoni', 'PROTEIN');
insert into Ingredient (id, name, type) values ('SZPA', 'szynka parmenska', 'PROTEIN');
insert into Ingredient (id, name, type) values ('BOCZ', 'boczek', 'PROTEIN');
insert into Ingredient (id, name, type) values ('SPPI', 'spinata picante', 'PROTEIN');
insert into Ingredient (id, name, type) values ('CHOR', 'chorizo', 'PROTEIN');
insert into Ingredient (id, name, type) values ('PAPR', 'papryka', 'VEGGIE');
insert into Ingredient (id, name, type) values ('PCHI', 'papryczki chilli', 'VEGGIE');
insert into Ingredient (id, name, type) values ('CEBU', 'cebula', 'VEGGIE');
insert into Ingredient (id, name, type) values ('CCEB', 'czerwona cebula', 'VEGGIE');
insert into Ingredient (id, name, type) values ('POMC', 'pomidorki cherry', 'VEGGIE');
insert into Ingredient (id, name, type) values ('KUKU', 'kukurydza', 'VEGGIE');
insert into Ingredient (id, name, type) values ('BAZY', 'bazylia', 'VEGGIE');
insert into Ingredient (id, name, type) values ('ANAN', 'ananas', 'VEGGIE');
insert into Ingredient (id, name, type) values ('COLI', 'czarne oliwki', 'VEGGIE');
insert into Ingredient (id, name, type) values ('ZOLI', 'zielone oliwki', 'VEGGIE');
insert into Ingredient (id, name, type) values ('PIEC', 'pieczarki', 'VEGGIE');
insert into Ingredient (id, name, type) values ('JALA', 'jalapeno', 'VEGGIE');
insert into Ingredient (id, name, type) values ('PEST', 'pesto', 'VEGGIE');
insert into Ingredient (id, name, type) values ('RUKO', 'rukola', 'VEGGIE');
insert into Ingredient (id, name, type) values ('SZCZ', 'szczypior', 'VEGGIE');
insert into Ingredient (id, name, type) values ('MOZZ', 'mozzarella', 'CHEESE');
insert into Ingredient (id, name, type) values ('RICO', 'ricotta', 'CHEESE');
insert into Ingredient (id, name, type) values ('GORG', 'gorgonzola', 'CHEESE');
insert into Ingredient (id, name, type) values ('FETA', 'feta', 'CHEESE');
insert into Ingredient (id, name, type) values ('PARM', 'parmezan', 'CHEESE');
insert into Ingredient (id, name, type) values ('S---', 'brak sosu', 'SAUCE');
insert into Ingredient (id, name, type) values ('SPOM', 'sos pomidorowy', 'SAUCE');
insert into Ingredient (id, name, type) values ('SBBQ', 'sos BBQ', 'SAUCE');
insert into Ingredient (id, name, type) values ('SSMI', 'sos śmietanowy', 'SAUCE');